# Generated by Django 4.2.6 on 2023-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('role', 'username'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Соискатель'), ('HR', 'HR компании-партнера'), ('STAFF', 'Сотрудник Яндекса')], default='student', max_length=9, verbose_name='Роль'),
        ),
    ]
