# Generated by Django 4.2.6 on 2023-10-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentuser_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='currency',
        ),
    ]
