# Generated by Django 4.2.6 on 2023-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_alter_hruser_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='birthdate',
            field=models.DateField(default='1900-01-01', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='brief',
            field=models.TextField(default=None, max_length=1024, verbose_name='О себе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='course',
            field=models.CharField(max_length=128, null=True, verbose_name='Дополнительное образование'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='course_year',
            field=models.IntegerField(default=None, verbose_name='Год окончания курсов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='cv',
            field=models.FileField(null=True, upload_to='students/cvs/', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='education',
            field=models.CharField(max_length=128, null=True, verbose_name='Основное образование'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='education_year',
            field=models.IntegerField(default=None, verbose_name='Год окончания учебного заведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='experience',
            field=models.CharField(default=None, max_length=128, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='format',
            field=models.CharField(default=None, max_length=128, verbose_name='Формат работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='level',
            field=models.CharField(default=None, max_length=128, verbose_name='Уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='location',
            field=models.CharField(default=None, max_length=32, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='students/photoes/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='portfolio',
            field=models.FileField(null=True, upload_to='students/portfolios/', verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='position',
            field=models.CharField(default=None, max_length=128, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Желаемый доход'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='seeking_for',
            field=models.BooleanField(default=True, verbose_name='Статус поиска'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='telegram',
            field=models.CharField(max_length=32, null=True, verbose_name='Telegram'),
        ),
    ]
