# Generated by Django 4.2.6 on 2023-10-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_skill_tag_vacancy'),
        ('users', '0005_studentuser_birthdate_studentuser_brief_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='career.skill', verbose_name='Навыки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_activities', to='users.studentuser', verbose_name='Соискатель')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_activities', to='career.activity', verbose_name='Активность')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='users.studentuser', verbose_name='Соискатель')),
            ],
        ),
        migrations.AddField(
            model_name='studentuser',
            name='activities',
            field=models.ManyToManyField(through='users.StudentsActivities', to='career.activity', verbose_name='Активности'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='skills',
            field=models.ManyToManyField(through='users.StudentsSkills', to='career.skill', verbose_name='Навыки'),
        ),
    ]
