version: '3.3'
services:

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    volumes:
      - db_value:/var/lib/postgresql/data/

  career_tracker_hr:
    build: ../career_tracker_hr/
    restart: always
    #volumes:
    #  - static_value:app/static
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
     # - static_value:/var/html/static/
    depends_on:
      - career_tracker_hr   
    
volumes:
  db_value:
  static_value: