# Generated by Django 4.2.6 on 2023-10-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(help_text='Выберите навыки', related_name='vacancy_skill', through='career.SkillVacancy', to='users.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги', related_name='vacancy_tag', through='career.TagVacancy', to='career.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tagvacancy',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='tagvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='skillvacancy',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='users.skill', verbose_name='Навык'),
        ),
        migrations.AddField(
            model_name='skillvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='resp',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentuser', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='resp',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='career.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.studentuser', verbose_name='favourite'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='career.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddConstraint(
            model_name='skillvacancy',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skill'), name='vacancy_skill'),
        ),
    ]
