# Generated by Django 4.2.6 on 2023-10-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentsskills_studentsactivities_and_more'),
        ('career', '0002_skill_tag_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Ваканcия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='additional_info',
            field=models.TextField(default='2023-10-23', verbose_name='Дополнительная информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default='123', max_length=128, verbose_name='Название компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='reject_letter',
            field=models.TextField(default='', verbose_name='Отказ соискателю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(to='career.tag'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.CreateModel(
            name='VacancySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigth', models.IntegerField(verbose_name='Вес навыка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(through='career.VacancySkills', to='career.skill', verbose_name='Требуемые навыки'),
        ),
    ]
