# Generated by Django 4.2.6 on 2023-10-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_vacancy_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillvacancy',
            old_name='weigth',
            new_name='weight',
        ),
    ]
