# Generated by Django 4.2.6 on 2023-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_invitation_vacancy_alter_resp_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillvacancy',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес навыка'),
        ),
    ]
