# Generated by Django 4.2.6 on 2023-10-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_alter_skillvacancy_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillvacancy',
            name='weight',
            field=models.IntegerField(verbose_name='Вес навыка'),
        ),
        migrations.AlterField(
            model_name='tagvacancy',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.tag', unique=True, verbose_name='Тег'),
        ),
    ]
