# Generated by Django 4.2.6 on 2023-10-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_alter_skillvacancy_weight_alter_tagvacancy_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagvacancy',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='career.tag', verbose_name='Тег'),
        ),
    ]
