# Generated by Django 4.2.6 on 2023-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_alter_tagvacancy_tag_tagvacancy_vacancy_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Заработная плата'),
        ),
    ]
