# Generated by Django 4.2.6 on 2023-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_vacancy_currency_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Валюта'),
        ),
    ]
