# Generated by Django 4.2.6 on 2023-10-30 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_alter_vacancy_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateField(default=datetime.date(2023, 10, 30), verbose_name='Дата публикации'),
        ),
    ]
