name: career_tracker

on:
  workflow_dispatch:

jobs:
  
  build_and_push_to_docker_hub:

    name: Build and then push docker image to DockerHub

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: career_tracker_hr/
        push: true
        tags: beskrovniibv/career_tracker_hr:hackatone


  deploy:
    
    if: github.ref_name == 'main'
    
    name: Deploy image on the server

    runs-on: ubuntu-latest

    needs: build_and_push_to_docker_hub

    steps:
    - name: Executing remote SSH to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_HOST_USER }}
        key: ${{ secrets.SSH_HOST_PUBLIC }}
        script: |
          sudo docker compose stop
          sudo docker compose rm career_tracker_hr -sf
          sudo docker rmi ${{ secrets.BACKEND_IMAGE }}
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} > .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo DEBUG=False >> .env
          echo POSTGRES_DB=${{ secrets.DB_NAME }} > .postgresql
          echo POSTGRES_USER=${{ secrets.DB_USER }} >> .postgresql
          echo POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} >> .postgresql
          sudo docker compose up -d
          sudo docker compose exec career_tracker_hr python manage.py makemigrations
          sudo docker compose exec career_tracker_hr python manage.py migrate
          sudo docker compose exec career_tracker_hr python manage.py collectstatic --no-input
